InventorySystemThesis/InventorySystemThesis/Models/Inventory/TakeAwaysInvoices/TAInvoices.cs
using InventorySystemThesis.Models.Inventory.Table;
using InventorySystemThesis.Models.Inventory.TakeAways;
using InventorySystemThesis.Models.Inventory.TakeAwaysInvoices;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace InventorySystemThesis.Models.Inventory.TakeAwaysInvoices
{
    [Table("TakeAwaysInvoice", Schema = "dbo")]
    public class TAInvoices
    {
        [Key]
        [Required]
        public string InvoicesId { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string? CustomerName { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string? PhoneNumber { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string? Address { get; set; }

        [Column(TypeName = "float")]
        public float Tax{ get; set; }

        [Column(TypeName = "float")]
        public float Discount { get; set; }

        [Column(TypeName = "float")]
        [Required]
        public float TotalPaidUSD{ get; set; }

        [Column(TypeName = "float")]
        public float TotalPaidKHR { get; set; }

        [Column(TypeName = "float")]
        [Required]
        public float RecievedAmountUSD{ get; set; }

        [Column(TypeName = "float")]
        public float RecievedAmountKHR { get; set; }

        [Column(TypeName = "float")]
        public float ChangedAmountUSD{ get; set; }

        [Column(TypeName = "float")]
        public float ChangedAmountKHR{ get; set; }

        [Column(TypeName = "datetime")]
        public DateTime createAt{ get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string createBy { get; set; }
        
        [Column(TypeName = "datetime")]
        public DateTime? updateAt { get; set; }

        [Column(TypeName = "nvarchar(125)")]
        public string? updateBy { get; set; }
   

        [Column(TypeName = "varchar(5)")]
        public string Status { get; set; }

        public int TakeAwayId { get; set; }

        public virtual TakeAway TakeAway { get; set; }

        public List<TAInvoicesDetail> InvoicesDetail { get; set; }


    }
}

InventorySystemThesis/InventorySystemThesis/Controllers/TAInvoicesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using InventorySystemThesis.Models.Inventory.Invoices;
using InventorySystemThesis.Models.Inventory.TakeAwaysInvoices;
using InventorySystemThesis.Repo.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class TAInvoicesController : Controller
    {
        private readonly ITAInvoicesRepo _iinvoicesRepo;
        private readonly ITakeAwaysRepo _itakeawaysRepo;

        public TAInvoicesController(ITAInvoicesRepo iinvoicesRepo, ITakeAwaysRepo itakeawaysRepo)
        {
            _iinvoicesRepo = iinvoicesRepo;
            _itakeawaysRepo = itakeawaysRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> InvoicesList(DateTime from, DateTime to)
        {

            if (from == default(DateTime) || to == default(DateTime))
            {
                from = DateTime.Now;
                to = DateTime.Now;
                ViewBag.from = from.Date.ToString("yyyy-MM-dd");
                ViewBag.to = to.Date.ToString("yyyy-MM-dd");

            }
            else
            {
                ViewBag.from = from.Date.ToString("yyyy-MM-dd");
                ViewBag.to = to.Date.ToString("yyyy-MM-dd");

            }
            ViewBag.InvoiceList = await _iinvoicesRepo.InvoicesBydate(from, to);
            return View();

        }
        public IActionResult TASale()
        {
            return View();

        }


        [HttpPost]
        public async Task<IActionResult> InvoicePrint(TAInvoices invoices)
        {
            invoices.updateBy=HttpContext.Session.GetString("username");

            return View(await _iinvoicesRepo.PaidInvoice(invoices));
        }

        [HttpGet]
        public async Task<IActionResult> InvoicePrint(string InvoicesId , string exchangeRate)
        {

            return View(await _iinvoicesRepo.FindById(InvoicesId));
        }


        [HttpGet]
        public IActionResult InsertInvoice(int taid,string name)
        {

            ViewBag.taid = taid;
            ViewBag.taname = name;
            return View();
        }


        [HttpPost]
        public async Task<JsonResult> InsertInvoice(TAInvoices invoices)
        {
            try
            {
                invoices.createBy = HttpContext.Session.GetString("username");
                await _iinvoicesRepo.AddeInvoices(invoices);
                if (invoices != null)
                {
                    await _itakeawaysRepo.UpdateUnavailable(invoices.TakeAwayId);
                    return new JsonResult(Ok(invoices));
                }

                else
                    return new JsonResult(BadRequest());
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());
            }
        }



        [HttpGet]
        public async Task<IActionResult> UpdateInvoice(int taid, string name)
        {
            ViewBag.name = name;
            var inv = await _iinvoicesRepo.FindByTakeAwaysId(taid);
            return View(inv);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateInvoice(TAInvoices invoices)
        {
            try
            {
                invoices.updateBy = HttpContext.Session.GetString("username");
                var inv = await _iinvoicesRepo.UpdateInvoice(invoices);
                if (invoices != null)
                    return new JsonResult(Ok(inv));
                else
                    return new JsonResult(BadRequest());
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());
            }
        }


        [HttpPost]
        public async Task<JsonResult> PaidInvoice(TAInvoices invoices)
        {
            try
            {
                var ivn = await _iinvoicesRepo.PaidInvoice(invoices);
                return new JsonResult(Ok(ivn));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> VoidInvoice(string id)
        {
            try
            {
                return new JsonResult(Ok(await _iinvoicesRepo.VoidInvoice(id, HttpContext.Session.GetString("username"))));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> FindInvoiceById(string id)
        {
            try
            {
                return new JsonResult(await _iinvoicesRepo.FindById(id));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }


        [HttpPost]
        public async Task<JsonResult> validateUpdateQty(int invoiceDetailid, float newQty)
        {
            try
            {

                return new JsonResult(Ok(await _iinvoicesRepo.validateUpdateQty(invoiceDetailid, newQty)));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> validateInsertQty(int menuItemId, float Qty)
        {
            try
            {

                return new JsonResult(Ok(await _iinvoicesRepo.validateInsertQty(menuItemId, Qty)));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }


    }
}

InventorySystemThesis/InventorySystemThesis/Views/TAInvoices/TASale.cshtml
@{
    var taList = await TakeAwaysServices.TakeAwaysList();
}

<div class="panel panel-headline">
    <div class="panel-heading">
        <h3 class="panel-title">TakeAways Order</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            @foreach (var item in taList)
            {
            <div class="col-md-3">
                <div class="metric">
                    @if (item.Status != "Y")
                    {
                        <a asp-action="UpdateInvoice" asp-controller="TAInvoices" asp-route-taid="@item.Id" asp-route-name="@item.Name" type="button" class="btn btn-warning left" value="@item.Name">Order More</a>
                        <p>
                            <span class="title">No. @item.Name</span>
                        </p>
                        <span class="label label-warning">Busy</span>
                    }
                    else
                    {
                        <a asp-action="InsertInvoice" asp-controller="TAInvoices" asp-route-taid="@item.Id" asp-route-name="@item.Name"  type="button" class="btn btn-primary left" value="@item.Name">Click to Order</a>
                        <p>
                            <span class="title">No. @item.Name </span>
                        </p>
                        <span class="label label-success">Available</span>
                    }

                </div>
            </div>
            }
        </div>
    </div>
</div>
<!-- END OVERVIEW -->

InventorySystemThesis/InventorySystemThesis/Views/TAInvoices/invoicePrint.cshtml
@model TAInvoices;
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DotNetTec - Invoice html template bootstrap</title>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta.2/css/bootstrap.css'>
</head>
<body>
    <div class="container">
        <div class="card">
            <div>
                <center><img src="~/assets/img/res-logo.png" alt="restaurant Logo" width="100" height="100"></center>
                <h4 class="text-center">Angkor Home Restaurant</h4>
                <h6 class="text-center">#2A, Street Corner 106-118, Sangkat Beung Kork II, Khan Toul Kork, Phnom Penh</h6>
            </div>
            <div class="card-header">
                <span class="text-left"><strong>Invoice Date:</strong> @Model.createAt.ToShortDateString()</span>
                <span class="float-right"> <strong>InvoiceCode:</strong> @Model.InvoicesId</span>
                <br /><label class="label label-default"><strong>Customer Name :</strong> @Model.CustomerName</label>
                <span class="float-right"> <strong>Phone:</strong> @Model.PhoneNumber</span><br />
                <label class="label label-default"><strong>Customer Address :</strong> @Model.Address</label>
            </div>
            <div class="card-body">
                <div class="table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th class="center">#</th>
                                <th>Item</th>
                                <th class="right">Unit Price ($)</th>
                                <th class="center">Qty</th>
                                <th class="right">UoM</th>
                                <th class="right">Disc (%)</th>
                                <th class="right">Total ($)</th>
                                @*<th class="right">Total (៛)</th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 1; }
                            @foreach (var item in Model.InvoicesDetail)
                            {
                                <tr>

                                    <td class="center">@i</td>
                                    <td>@item.MenuItem.MenuItemNameKH</td>
                                    <td class="right">@item.MenuItem.Price</td>

                                    <td class="center">@item.Qty</td>
                                    <th class="right">@item.MenuItem.Stock.UnitOfMeasure.NameKH</th>
                                    <td class="right">@item.Discount</td>
                                    <td class="right">@item.Price</td>
                                </tr>
                                i++;
                            }

                            @*@{
                        if (SalesInvList != null)
                        {
                            int i = 1;

                            foreach (var invprt in SalesInvList)
                            {
                                <td class="center">@i</td>
                                <td>@invprt.ProductName</td>
                                <td class="right">@invprt.UnitPrice</td>

                                <td class="center">@invprt.Qty</td>
                                <th class="right">@invprt.UoM</th>
                                <td class="right">@invprt.TotalPriceUSD</td>
                                <td class="right">@invprt.TotalPriceKHR</td>
                                i++;
                                totalUSD += invprt.TotalPriceUSD;
                                totalKHR += invprt.TotalPriceKHR;
                            }

                        }*@
                            @*else
                        {

                            <td class="center">1</td>
                            <td class="left strong">Origin License</td>
                            <td class="left">Extended License</td>

                            <td class="right">$999,00</td>
                            <td class="center">1</td>
                            <td class="right">$999,00</td>

                        }*@

                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-5">

                    </div>

                    <div class="col-lg-4 col-sm-5 ml-auto">
                        <table class="table table-clear">
                            <tbody>
                                @*<tr>
                                <td class="left">
                                    <strong>Subtotal</strong>
                                </td>
                                <td class="right">$8.497,00</td>
                            </tr>
                            <tr>
                                <td class="left">
                                    <strong>Discount (20%)</strong>
                                </td>
                                <td class="right">$1,699,40</td>
                            </tr>
                            <tr>
                                <td class="left">
                                    <strong>VAT (10%)</strong>
                                </td>
                                <td class="right">$679,76</td>
                            </tr>*@
                                <tr>
                                    <td class="left">
                                        <strong>Discount</strong>
                                    </td>
                                    <td class="right">
                                        <strong>% @Model.Discount</strong>
                                    </td>
                                </tr>

                                <tr>
                                    <td class="left">
                                        <strong>Total</strong>
                                    </td>
                                    <td class="right">
                                        <strong>$ @Model.TotalPaidUSD.ToString("0.00")</strong>
                                        <br />
                                        <strong>៛ @Model.TotalPaidKHR</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="left">
                                        <strong>Recieve Amount (USD)</strong>
                                    </td>
                                    <td class="right">
                                        <strong>$ @Model.RecievedAmountUSD.ToString("0.00")</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="left">
                                        <strong>Recieve Amount (KHR)</strong>
                                    </td>
                                    <td class="right">
                                        <strong>៛ @Model.RecievedAmountKHR</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="left">
                                        <strong>Change</strong>
                                    </td>
                                    <td class="right">
                                        <strong>$ @Model.ChangedAmountUSD.ToString("0.00")</strong>
                                        <br />
                                        <strong>៛ @Model.ChangedAmountKHR</strong>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="left">
                                        <span>
                                            RATE : 1$ =
                                        </span>
                                        <span id="exchange_rate">
                                        </span>
                                        <span>
                                            ៛
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    var exchangeRate = 0.00;
    $(document).ready(function () {
        $.ajax({
            url: "/SystemConfigs/GetSysConfigByKey",
            datatype: "json",
            type: "get",
            data: { key: "EXCHANGE_RATE" },
            success: function (response) {
                //    alert(JSON.stringify(response));
                exchangeRate = parseFloat(response.value);
                $("#exchange_rate").text(exchangeRate);
                
                //This execute when entire finished loaded
                window.print();
            },
            error: function (err) {
                console.log("Error get datae :" + err);
            }
        });
    });
</script>