InventorySystemThesis/InventorySystemThesis/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using InventorySystemThesis.Models.Inventory.Invoices;
using InventorySystemThesis.Repo.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class InvoicesController : Controller
    {
        private readonly IInvoicesRepo _iinvoicesRepo;
        private readonly ITableRepo _itableRepo;

        public InvoicesController(IInvoicesRepo iinvoicesRepo, ITableRepo itableRepo)
        {
            _iinvoicesRepo = iinvoicesRepo;
            _itableRepo = itableRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> InvoicesList(DateTime from, DateTime to)
        {

            if (from == default(DateTime) || to == default(DateTime))
            {
                from = DateTime.Now;
                to = DateTime.Now;
                ViewBag.from = from.Date.ToString("yyyy-MM-dd");
                ViewBag.to = to.Date.ToString("yyyy-MM-dd");

            }
            else
            {
                ViewBag.from = from.Date.ToString("yyyy-MM-dd");
                ViewBag.to = to.Date.ToString("yyyy-MM-dd");

            }
            ViewBag.InvoiceList = await _iinvoicesRepo.InvoicesBydate(from, to);
            return View();

        }
        public IActionResult TableSale()
        {
            return View();

        }

        //[HttpPost]
        //public async Task<JsonResult> InvoicesList(DateTime from, DateTime to)
        //{
        //    if (from == default(DateTime) || to == default(DateTime))
        //    {
        //        from = DateTime.Now;
        //        to = DateTime.Now;
        //    }

        //    return new JsonResult(Ok(await _iinvoicesRepo.InvoicesBydate(from, to)));
        //}




        [HttpPost]
        public async Task<IActionResult> InvoicePrint(Invoices invoices)
        {
            invoices.updateBy=HttpContext.Session.GetString("username");

            return View(await _iinvoicesRepo.PaidInvoice(invoices));
        }

        [HttpGet]
        public async Task<IActionResult> InvoicePrint(string InvoicesId , string exchangeRate)
        {

            return View(await _iinvoicesRepo.FindById(InvoicesId));
        }


        //[HttpPost]
        //public async Task<IActionResult> VoidInv(string id)
        //{
        //    try
        //    {
        //        var invoiceitemvoid = await _iinvoicesRepo.FindById(id);
        //        invoiceitemvoid.Status = "Void";
        //        ViewBag.InvoiceList = await _iinvoicesRepo.UpdateInvoice(invoiceitemvoid);

        //        //input stock logic
        //        List<Product> salesupRange = new List<Product>();
        //        var salesInvList = _isalesRepo.FindByInvCode(invoiceitemvoid.InvoicesId);
        //        foreach (var item in salesInvList)
        //        {
        //            //query by productname in stock or query by productname and UoM
        //            Product productsRes = new Product(); //should be return from repo
        //            //after get response qty in stock + qty item.qty
        //            //productsRes.qty+=item.qty;
        //            salesupRange.Add(productsRes);

        //        }
        //        //insert list back to product using async

        //        // await iproductRepo.AddRange(salesupRange);

        //        //end stock logic

        //        //update table status logic

        //        //query table from using itableRepo by invoiceitemvoid.TableNo 

        //        //after get response update status 
        //        //update tbl status to != Y using async
        //        // await itableRepo.Update(tblRes)

        //        //end table status logic
        //        return RedirectToAction("InvoicesList");

        //    }
        //    catch (Exception)
        //    {
        //        return View();
        //    }
        //}

        //[HttpPost]
        //public async Task<IActionResult> UpdateInvoicePaid(Invoices invoices)
        //{
        //    try
        //    {
        //        var invoiceitem = await _iinvoicesRepo.FindById(invoices.InvoicesId);
        //        invoiceitem.Status = "Paid";
        //        invoiceitem.RecievedAmountUSD = invoices.RecievedAmountUSD;
        //        invoiceitem.ChangedAmountUSD = invoiceitem.TotalPaidUSD - invoices.RecievedAmountUSD;
        //        ViewBag.InvoiceList = await _iinvoicesRepo.UpdateInvoice(invoiceitem);
        //        return RedirectToAction("InvoicesList");
        //    }
        //    catch (Exception)
        //    {
        //        return View();
        //    }
        //}

        [HttpGet]
        public IActionResult InsertInvoice(int tblid,string tblname , int floor)
        {

            ViewBag.tblid = tblid;
            ViewBag.tblnumber = tblname;
            ViewBag.floor = floor;
            return View();
        }


        [HttpPost]
        public async Task<JsonResult> InsertInvoice(Invoices invoices)
        {
            try
            {
                invoices.createBy = HttpContext.Session.GetString("username");
                await _iinvoicesRepo.AddeInvoices(invoices);
                if (invoices != null)
                {
                    await _itableRepo.UpdateUnavailable(invoices.TableID);
                    return new JsonResult(Ok(invoices));
                }

                else
                    return new JsonResult(BadRequest());
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());
            }
        }



        [HttpGet]
        public async Task<IActionResult> UpdateInvoice(int tblid, string tblname, int floor)
        {
            ViewBag.tblnumber = tblname;
            ViewBag.floor = floor;
            var inv = await _iinvoicesRepo.FindByTableId(tblid);
            return View(inv);
        }

        [HttpPost]
        public async Task<JsonResult> UpdateInvoice(Invoices invoices)
        {
            try
            {
                invoices.updateBy = HttpContext.Session.GetString("username");
                var inv = await _iinvoicesRepo.UpdateInvoice(invoices);
                if (invoices != null)
                    return new JsonResult(Ok(inv));
                else
                    return new JsonResult(BadRequest());
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());
            }
        }


        [HttpPost]
        public async Task<JsonResult> PaidInvoice(Invoices invoices)
        {
            try
            {
                var ivn = await _iinvoicesRepo.PaidInvoice(invoices);
                return new JsonResult(Ok(ivn));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> VoidInvoice(string id)
        {
            try
            {
                return new JsonResult(Ok(await _iinvoicesRepo.VoidInvoice(id, HttpContext.Session.GetString("username"))));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> FindInvoiceById(string id)
        {
            try
            {
                return new JsonResult(await _iinvoicesRepo.FindById(id));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }


        [HttpPost]
        public async Task<JsonResult> validateUpdateQty(int invoiceDetailid, float newQty)
        {
            try
            {

                return new JsonResult(Ok(await _iinvoicesRepo.validateUpdateQty(invoiceDetailid, newQty)));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }

        [HttpPost]
        public async Task<JsonResult> validateInsertQty(int menuItemId, float Qty)
        {
            try
            {

                return new JsonResult(Ok(await _iinvoicesRepo.validateInsertQty(menuItemId, Qty)));
            }
            catch (Exception)
            {
                return new JsonResult(BadRequest());

            }
        }


        //[HttpGet]
        //public IActionResult SalesInvCodeList(string invCode)
        //{

        //    var salesInvList =_isalesRepo.FindByInvCode(invCode);

        //    if (salesInvList == null)
        //    {
        //        salesInvList = new List<Sales> { new Sales { TableID = 1 } ,new Sales { TableID=2} };
        //    };
        //    ViewBag.salesInvList = salesInvList;
        //    return Ok(salesInvList);
        //    // return View();
        //}


    }
}

InventorySystemThesis/InventorySystemThesis/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventorySystemThesis.Models.Inventory.Products;
using InventorySystemThesis.Models.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using InventorySystemThesis.Repo.IRepository;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class MenuItemsController : Controller
    {
        private readonly IMenuItemRepo _imenuItemRepo;

        public MenuItemsController(IMenuItemRepo imenuItemRepo)
        {
            _imenuItemRepo = imenuItemRepo;
        }
        public IActionResult MenuItemsList()
        {
            var menuItem = _imenuItemRepo.MenuItemList();
            ViewBag.MenuItems = menuItem;
            return View();
        }

        [HttpPost]
        public IActionResult CreateMenuItem(MenuItem menuItem)
        {



           _imenuItemRepo.SaveMenuItem(menuItem);
            return RedirectToAction("MenuItemsList");

         
        }

        [HttpGet]
        public IActionResult UpdateMenuItem(int id)
        {
            var menuItem = _imenuItemRepo.FindMenuItemById(id);
            return Ok(menuItem);
        }

        [HttpGet]
        public IActionResult FindById(int id)
        {
            var menuItem = _imenuItemRepo.FindMenuItemById(id);
            return Ok(menuItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult   UpdateMenuItem(MenuItem menuItem)
        {
            _imenuItemRepo.UpdateMenuItem(menuItem);

            return RedirectToAction(nameof(MenuItemsList));
        }

        // [HttpPost]
        /*public async Task<JsonResult> Remove(int id)
        {
            bool status = false;

            var menuItem = await imenuItemRepo.MenuItems.FindAsync(id);
           imenuItemRepo.MenuItems.Remove(menuItem);
            try
            {
             await imenuItemRepo.SaveChangesAsync();
                status = true;
            }
            catch (Exception)
            {

                throw;
            }

            return new JsonResult(new { data = status});

        }*/

        [HttpPost]
        public JsonResult DeletemenuItem(int id)
        {
            bool status = _imenuItemRepo.DelateMenuItem(id);

            return new JsonResult(new { data = status });
        }

    }
}

InventorySystemThesis/InventorySystemThesis/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventorySystemThesis.Models.Inventory.Table;
using InventorySystemThesis.Models.Services;
using Microsoft.AspNetCore.Authorization;
using InventorySystemThesis.Repo.IRepository;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class TablesController : Controller
    {
        
        private readonly ITableRepo _itableRepo;
        public TablesController(ITableRepo itableRepo)
        {
            _itableRepo = itableRepo;
        }

        // GET: Tables
        public IActionResult table()
        {
            var tables = _itableRepo.TableList();
            ViewBag.Tables = tables;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveTable(Tables tables)
        {
            tables.Status = "Y";

            _itableRepo.SaveTable(tables);
            return RedirectToAction("table");
        }




        // GET: Tables/Edit/5

        public IActionResult EditTable(int id)
        {
            var tables = _itableRepo.FindTableById(id);
            if (tables == null)
            {
                return NotFound();
            }
            return Ok(tables);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditTable(Tables tables)
        {
            _itableRepo.UpdateTable(tables);
            return RedirectToAction(nameof(table));
        }




        // GET: Tables/Delete/5
        /*public async Task<IActionResult> Remove(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tables = await _context.Tables
                .FirstOrDefaultAsync(m => m.TableID == id);
            if (tables == null)
            {
                return NotFound();
            }

            return View(tables);
        }*/

        // POST: Tables/Delete/5
        [HttpPost]
        public JsonResult DeleteTable(int id)
        {
            bool status = _itableRepo.DeleteTable(id);

            return new JsonResult(new { data = status });
        }


        /*
                private bool TablesExists(int id)
                {
                    return _context.Tables.Any(e => e.TableID == id);
                }
        */


    }
}

InventorySystemThesis/InventorySystemThesis/Controllers/TakeAwaysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using InventorySystemThesis.Models.Inventory.Table;
using InventorySystemThesis.Models.Services;
using Microsoft.AspNetCore.Authorization;
using InventorySystemThesis.Models.Inventory.TakeAways;
using InventorySystemThesis.Repo.IRepository;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class TakeAwaysController : Controller
    {
        
        private readonly ITakeAwaysRepo _itakeAwaysRepo;
        public TakeAwaysController(ITakeAwaysRepo itakeAwaysRepo)
        {
            _itakeAwaysRepo = itakeAwaysRepo;
        }

        // GET: Tables
        public IActionResult TakeAway()
        {
            var ta = _itakeAwaysRepo.TakeAwayList();
            ViewBag.TakeAway = ta;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveTakeAways(TakeAway takeAway)
        {
            takeAway.Status = "Y";

            _itakeAwaysRepo.SaveTakeAway(takeAway);
            return RedirectToAction(nameof(TakeAway));
        }




        // GET: Tables/Edit/5

        public IActionResult TakeAways(int id)
        {
            var takeaways = _itakeAwaysRepo.FindTaById(id);
            if (takeaways == null)
            {
                return NotFound();
            }
            return Ok(takeaways);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditTakeAways(TakeAway takeAway)
        {
            _itakeAwaysRepo.UpdateTa(takeAway);
            return RedirectToAction(nameof(takeAway));

        }

        [HttpPost]
        public JsonResult DeleteTakeAways(int id)
        {
            bool status = _itakeAwaysRepo.DeleteTa(id);

            return new JsonResult(new { data = status });
        }
        /*  [HttpPost]
          public async Task<JsonResult> DeleteTakeAways(int id)
          {
              var ta = await _context.TakeAways.FindAsync(id);
              bool status = true;
              _context.TakeAways.Remove(ta);
              try
              {
                  await _context.SaveChangesAsync();

              }
              catch (Exception )
              {
                  status = false;

              }
              await _context.SaveChangesAsync();
              return new JsonResult(new { data = status });

          }*/
    }
}

InventorySystemThesis/InventorySystemThesis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>@ViewData["Title"] - Angkor Home</title>
    <!--DT CSS-->
    @*<link rel="stylesheet" href="~/css/site.css" />*@
    <link rel="stylesheet" href="~/datatable/datatables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css" />
    @* <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css"/> *@
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap1.min.css" />*@
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="~/assets/vendor/chartist/css/chartist-custom.css">
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/assets/css/main.css">
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="~/assets/css/demo.css">
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <!-- ICONS -->
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    @*<link rel="icon" type="image/png" sizes="96x96" href="~/assets/img/favicon.png">*@
    <link rel="icon" type="image/png" sizes="120x120" href="~/assets/img/res-logo.png">
    @RenderSection("Style", required: false)


</head>
<body>
    <!-- WRAPPER -->
    <div id="wrapper">
        <!-- NAVBAR -->
        @{ await Html.RenderPartialAsync("_header");}
        <!-- END NAVBAR -->
        <!-- LEFT SIDEBAR -->
        @{ await Html.RenderPartialAsync("_leftnav");}
        <!-- END LEFT SIDEBAR -->
        <!-- MAIN -->
        <div class="main">
            <!-- MAIN CONTENT -->
            <div class="main-content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <!-- END MAIN CONTENT -->
        </div>
        <!-- END MAIN -->
        <div class="clearfix"></div>
        <footer>
            <div class="container-fluid">
                <p class="copyright">&copy; 2017 <a href="https://www.themeineed.com" target="_blank">Theme I Need</a>. All Rights Reserved.</p>
            </div>
        </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="~/assets/vendor/chartist/js/chartist.min.js"></script>
    <script src="~/assets/scripts/klorofil-common.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/datatable/datatables.js"></script>
    @* <script src="https://code.jquery.com/jquery-3.5.1.js"></script> *@
    @* <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script> *@
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.colVis.min.js"></script>
   
    @RenderSection("Scripts", required: false)

</body>
</html>

InventorySystemThesis/InventorySystemThesis/Views/Shared/_leftnav.cshtml
<div id="sidebar-nav" class="sidebar">
    <div class="sidebar-scroll" id="myDiv">
        <nav>
            <ul class="nav">
                @if (Context.Session.GetString("rolename") == "Admin")
                {
                    <li>
                        <a is-active-route asp-controller="SystemConfigs" asp-action="SystemConfigsList" class=""><i class="lnr lnr-cog"></i> <span>Systems Management</span></a>
                    </li>
                    <li>
                        <a is-active-route asp-controller="Accounts" asp-action="Users" class=""><i class="lnr lnr-user"></i> <span>Users Management</span></a>
                    </li>
                    <li>
                        <a is-active-route asp-controller="Stocks" asp-action="StocksList" class=""><i class="fa fa-database"></i> <span>Stocks Management</span></a>
                    </li>
                }
                <li><a is-active-route asp-controller="Tables" asp-action="table" class=""><i class="fa fa-table"></i> <span>Tables Management</span></a></li>
                <li><a is-active-route asp-controller="TakeAways" asp-action="TakeAway" class=""><i class="fa fa-truck"></i> <span>TakeAways Management</span></a></li>
                <li><a is-active-route asp-controller="CategoryModels" asp-action="CategoryList" class=""><i class="fa fa-filter"></i> <span>Categories Management</span></a></li>
                <li><a is-active-route asp-controller="MenuItems" asp-action="MenuItemsList" class=""><i class="lnr lnr-dinner"></i><span>Menu Items Management</span></a></li>
                <li><a is-active-route asp-controller="Invoices" asp-action="TableSale" class=""><i class="lnr lnr-cart"></i> <span>Sales Management</span></a></li>
                <li><a is-active-route asp-controller="TAInvoices" asp-action="TASale" class=""><i class="lnr lnr-cloud-upload"></i> <span>T-A Sales Management</span></a></li>
                <li><a is-active-route asp-controller="Invoices" asp-action="InvoicesList" class=""><i class="fa fa-credit-card"></i> <span>Invoices Management</span></a></li>
                <li><a is-active-route asp-controller="TAInvoices" asp-action="InvoicesList" class=""><i class="fa fa-paypal"></i> <span>T-A Invoices Management</span></a></li>

                @*<li>
            <a href="#subPagesMenu" data-toggle="collapse" class="collapsed"><i class="lnr lnr-circle-minus"></i> <span>MenuItems</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
            <div id="subPagesMenu" class="collapse ">
                <ul class="nav">
                    <li><a is-active-route asp-controller="MenuItems" asp-action="MenuItemsList" class="">MenuItemList</a></li>
                    <li><a is-active-route asp-controller="MenuItemTypes" asp-action="MenuItemTypeList" class="">MenuItemType</a></li>
                </ul>

            </div>
        </li>*@
                @*<li>
            <a href="#subPagesInvoices" data-toggle="collapse" class="collapsed"><i class="lnr lnr-alarm"></i> <span>Invoices Maintence</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
            <div id="subPagesInvoices" class="collapse ">
                <ul class="nav">
                    <li><a is-active-route asp-controller="Invoices" asp-action="InvoicesList" class="">Invoices List</a></li>
                </ul>

            </div>
        </li>*@

                @*<li><a asp-controller="Accounts" asp-action="Dashboard" class=""><i class="lnr lnr-home"></i> <span>Dashboard</span></a></li>*@
                @*<li><a href="elements.html" class=""><i class="lnr lnr-code"></i> <span>Elements</span></a></li>*@

                @*<li>
            <a href="#subPagesStock" data-toggle="collapse" class="collapsed"><i class="lnr lnr-circle-minus"></i> <span>Stocks Maintence</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
            <div id="subPagesStock" class="collapse ">
                <ul class="nav">
                    <li><a is-active-route asp-controller="Stocks" asp-action="StocksList" class="">Stocks List</a></li>
                </ul>

            </div>
        </li>*@

                @*
        <li><a is-active-route asp-controller="Invoices" asp-action="TableSale" class=""><i class="lnr lnr-cart"></i> <span>Sale Menu</span></a></li>
        <li><a is-active-route asp-controller="CategoryModels" asp-action="CategoryList" class=""><i class="fa fa-table"></i> <span>Category</span></a></li>
                *@
                @*<li><a href="charts.html" class=""><i class="lnr lnr-chart-bars"></i> <span>Charts</span></a></li>
        <li><a href="panels.html" class=""><i class="lnr lnr-cog"></i> <span>Panels</span></a></li>*@

                @*<li>
            <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i> <span>Reports</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
            <div id="subPages" class="collapse ">
                <ul class="nav">
                    <li><a href="#" class="">Sale Report</a></li>
                    <li><a href="#" class="">Sale Chart Report</a></li>
                    <li><a href="#" class="">Stock Report</a></li>
                </ul>
            </div>
        </li>*@
                @*<li><a href="tables.html" class=""><i class="lnr lnr-dice"></i> <span>Tables</span></a></li>
        <li><a href="typography.html" class=""><i class="lnr lnr-text-format"></i> <span>Typography</span></a></li>
        <li><a href="icons.html" class=""><i class="lnr lnr-linearicons"></i> <span>Icons</span></a></li>*@


            </ul>
        </nav>
    </div>
</div>
@*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@