InventorySystemThesis/InventorySystemThesis/Controllers/MenuItemTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InventorySystemThesis.Models.Inventory.Products;
using InventorySystemThesis.Models.Services;
using Microsoft.AspNetCore.Authorization;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class MenuItemTypesController : Controller
    {
        private readonly AppContexts _context;

        public MenuItemTypesController(AppContexts context)
        {
            _context = context;
        }

        // GET: MenuItemTypes
        public IActionResult MenuItemTypeList()

        {
            var menuItemtype = _context.MenuItemTypes.ToList();
            ViewBag.MenuItemTypes = menuItemtype;
            return View();
        }


        public ActionResult SaveMenuItemtype(MenuItemTypes menuItemtype)
        {


            _context.MenuItemTypes.Add(menuItemtype);
            _context.SaveChanges();

            return RedirectToAction("MenuItemTypeList");
        }


        public async Task<IActionResult> Editmenu(int? id)
        {
            var menuItemtype = await _context.MenuItemTypes.FindAsync(id);
            if (menuItemtype == null)
            {
                return NotFound();
            }
            return Ok(menuItemtype);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editmenu(MenuItemTypes menuItemtype)
        {
            var existingtbl = await _context.MenuItemTypes.FindAsync(menuItemtype.MenuItemTypeId);

            existingtbl.MenuItemTypeName = menuItemtype.MenuItemTypeName;


            _context.MenuItemTypes.Update(existingtbl);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {

                throw e;
            }

            return RedirectToAction(nameof(MenuItemTypeList));
        }

        [HttpPost]
        public async Task<JsonResult> Remove(int id)
        {
            bool status = false;

            var menuItemtype = await _context.MenuItemTypes.FindAsync(id);
            _context.MenuItemTypes.Remove(menuItemtype);
            try
            {
                await _context.SaveChangesAsync();
                status = true;
            }
            catch (Exception)
            {

                throw;
            }

            return new JsonResult(new { data = status });

        }
    }
}

InventorySystemThesis/InventorySystemThesis/Views/MenuItemTypes/MenuItemTypeList.cshtml
@model InventorySystemThesis.Models.Inventory.Products.MenuItemTypes
@{
    ViewData["Title"] = "MenuItemTypeList";
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>

<span class="pull-right">
    <span class="pull-right"><a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#MenuItemtype_Modal">Create New Data</a></span>
</span>

<!--Create Popup Modal-->
<div class="modal fade" id="MenuItemtype_Modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">MenuItemType Information</h2>
            </div>
            <div class="modal-body">
                <form id="MenuItemtypeForm">

                    <div class="form-group">
                        <label asp-for="MenuItemTypeName" class="control-label"></label>
                        <input asp-for="MenuItemTypeName" class="form-control" />
                        <span asp-validation-for="MenuItemTypeName" class="text-danger"></span>
                    </div>

                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" id="btnCreate" class="btn btn-primary save">Create</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>


<!--Edit Popup Modal-->
<div class="modal fade" id="editModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Update Info</h2>
            </div>
            <form asp-action="Editmenu" asp-controller="MenuItemTypes" method="post">

                <div class="modal-body">
                    <input type="hidden" asp-for="MenuItemTypeId" class="menuItemtype_id" />
                    <div class="form-group">
                        <label asp-for="MenuItemTypeName" class="control-label"></label>
                        <input asp-for="MenuItemTypeName" class="form-control menuItemtype_name" />
                        <span asp-validation-for="MenuItemTypeName" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary save">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>


<table class="display table table-striped table-sm" id="ExampleDataTable">
    <thead>
        <tr>
            <th>
                MenuItemTypeName
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ViewBag.MenuItemTypes)
        {
            <tr>
                <td>
                    @item.MenuItemTypeName
                </td>
                <td>

                    <a href="#" class="btn-info btn-xs" data-toggle="modal" data-target="#editModal" onclick="click_update(@item.MenuItemTypeId)"><i class="fa fa-edit"></i>Edit</a>
                    <a href="#" onclick="click_delete(@item.MenuItemTypeId)" class="btn-danger btn-xs"><i class="fa fa-trash"></i> Remove </a>
                </td>
            </tr>
        }
    </tbody>
</table>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@*<script src="~/datatable/js/"></script>*@
<script>
    $(document).ready(function () {
        $('#ExampleDataTable').DataTable({
            "processing": false,
            "serverSide": false,
            "paging": true,
            "ordering": true,
            "info": false,
            "searching": true,
            dom: 'B<"clear">lfrtip',
            buttons: [
            {
                extend: 'csv',
                title: 'Data export',
                exportOptions: {
                    columns: [ 0 ]
                },
                 className: 'btn btn-xs btn-primary p-5 m-0 width-35 assets-export-btn export-csv ttip'

            },
            {
                extend: 'pdfHtml5',
                className: 'btn btn-xs btn-primary p-5 m-0 width-35 assets-export-btn export-pdf ttip',
                title: 'Data export'
            }
        ]
          });
        });
    @* }); *@

</script>
<script>
    function click_update(val) {
        $.ajax({
            //url :"/controller_name/action_name"
            url: "/MenuItemTypes/Editmenu",
            datatype: "json",
            type: "get",
            data: { id: val },
            success: function (response) {
                // alert(JSON.stringify(response));
                //$(.class).val(response.must_be_same_as_value_that_alert)
                $('.menuItemtype_id').val(response.menuItemTypeId);
                $('.menuItemtype_name').val(response.menuItemTypeName);



            },
            error: function (err) {
                console.log("Error get datae :" + err);
            }
        });
    }



function click_delete(val) {
    swal({
        title: "Are you sure?",
        text: "Once deleted, you will not be able to recover this MenuItemType!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
    }).then((willDelete) => {
        if (willDelete) {

            $.ajax({
                url: "/MenuItemTypes/Remove",
                datatype: "json",
                type: "post",
                data: { id: val },
                success: function (response) {
                    alert(JSON.stringify(response));

                    if (response.data) {
                        // swal("Good job!", "User has been deleted !", "success");
                        swal({
                            icon: 'success',
                            title: 'Good job!',
                            text: 'MenuItemType has been deleted !',
                            timer: 1500
                        })
                        setTimeout(function () { window.location.href = "/MenuItemTypes/MenuItemTypeList"; }, 2000);

                    }
                    else {
                        swal("Oops!", "Something went wrong !", "error");
                    }


                },
                error: function (err) {
                    console.log("Error get datae :" + err);
                }
            });

        } else {
            swal("Your MenuItemType is safe!");
        }
    });

}

</script>
<script>
    $(document).ready(function () {
        $("#btnCreate").click(function () {
            var tableFormData = $("#MenuItemtypeForm").serialize();

            $.ajax({
                type: "POST",
                url: "/MenuItemTypes/SaveMenuItemtype",
                data: tableFormData,
                success: function () {
                    window.location.href = "/MenuItemTypes/MenuItemTypeList";
                }
            })
        })

    })

</script>