InventorySystemThesis/InventorySystemThesis/Controllers/CategoryModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InventorySystemThesis.Models.Services;
using InventorySystemThesis.Models.Inventory.Categories;
using Microsoft.AspNetCore.Authorization;
using InventorySystemThesis.Repo.IRepository;

namespace InventorySystemThesis.Controllers
{
    [Authorize]
    public class CategoryModelsController : Controller
    {
        
        private readonly ICategoryRepo _icategoryRepo;
        public CategoryModelsController(ICategoryRepo icategoryRepo)
        {
            _icategoryRepo = icategoryRepo;
        }

        // GET: CategoryModels
        public IActionResult CategoryList()
        {
            var category = _icategoryRepo.CategoryList();
            ViewBag.CategoryModels = category;
            return View();
        }


        public ActionResult SaveCategory(Category category)
        {
            category.Status = "S";

            _icategoryRepo.SaveCategory(category);
            return RedirectToAction("CategoryList");
        }

        [HttpGet]
        public IActionResult EditCategory(int id)
        {
            var category = _icategoryRepo.FindCateById(id);
            if (category == null)
            {
                return NotFound();
            }
            return Ok(category);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCategory(Category category)
        {
            _icategoryRepo.UpdateCate(category);

            return RedirectToAction(nameof(CategoryList));
        }

        [HttpPost]
        public JsonResult DeleteCategory(int id)
        {
            bool status = _icategoryRepo.DeleteCate(id);

            return new JsonResult(new { data = status });
        }

        /*public async Task<JsonResult> Remove(int id)
        {
            var category = await _context.Category.FindAsync(id);
            bool Status = true;
            _context.Category.Remove(category);
            try
            {
                await _context.SaveChangesAsync();
               }
              catch (Exception)
            {
                Status = false;
            }

            await _context.SaveChangesAsync();
            return new JsonResult(new { data = Status });

        }
        private bool CategoryModelExists(int id)
        {
            return _context.Category.Any(e => e.CateID == id);
        }*/
    }
}

InventorySystemThesis/InventorySystemThesis/Views/CategoryModels/CategoryList.cshtml
@model InventorySystemThesis.Models.Inventory.Categories.Category
@*@{
        ViewData["Title"] = "CategoryList";
    }*@



@*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">*@
<style>
    .error {
        color: red;
        font-style: italic;
    }
</style>
<div class="">
    <span class="pull-right">
        <span class="pull-right"><a href="#" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#Category_Modal">Create New Category</a></span>
    </span>
    <table class="display table table-striped table-sm" id="ExampleDataTable" style="width:100%">
        <thead>
            <tr>
                <th>CateName</th>
                <th>CateNameKH</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.CategoryModels)
            {
                <tr>
                    <td>@item.CateName</td>
                    <td>@item.CateNameKH</td>
                    <td>
                        <a href="#" onclick="click_update(@item.CateID)" class="btn-info btn-xs" data-toggle="modal" data-target="#editModal"><i class="fa fa-edit"></i>Edit</a>
                        <a href="#" onclick="click_delete(@item.CateID)" class="btn-danger btn-xs"><i class="fa fa-trash"></i> Remove </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="Category_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form asp-action="SaveCategory" asp-controller="CategoryModels" method="post" id="frmModalCreate">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Category Information</h5>
                </div>
                <div class="modal-body">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active" id="uploadTab">
                            <div class="panel-body">
                                <div class="form-group">
                                    <label asp-for="CateName" class="control-label">Category Name</label>
                                    <input asp-for="CateName" class="form-control" />
                                </div>

                                <div class="form-group">
                                    <label asp-for="CateNameKH" class="control-label">Category Name KH</label>
                                    <input asp-for="CateNameKH" class="form-control" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary save">Save</button>
                </div>
            </div>
        </form>
    </div>
</div>



<!--Edit Popup Modal-->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Update Info</h5>
            </div>
            <form asp-action="EditCategory" asp-controller="CategoryModels" method="post">

                <div class="modal-body">
                    <input type="hidden" asp-for="CateID" class="Category_id" />
                    <div class="form-group">
                        <label asp-for="CateName" class="control-label"></label>
                        <input asp-for="CateName" class="form-control Cate_name" />
                        <span asp-validation-for="CateName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CateNameKH" class="control-label"></label>
                        <input asp-for="CateNameKH" class="form-control catenamekh" />
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary save">Save Change</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js"></script>*@
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
@*<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>*@
<script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/sweetalert/sweetalert.min.js"></script>



@*<script src="~/datatable/js/"></script>*@
<script>
    $(document).ready(function () {
        $('#ExampleDataTable').DataTable({
            "processing": false,
            "serverSide": false,
            "paging": true,
            "ordering": true,
            "info": false,
            "searching": true
        //    ,
        //    dom: 'B<"clear">lfrtip',
        //    buttons: [
        //    {
        //        extend: 'csv',
        //        title: 'Data export',
        //        exportOptions: {
        //            columns: [ 0 ]
        //        },
        //         className: 'btn btn-xs btn-primary p-5 m-0 width-35 assets-export-btn export-csv ttip'

        //    },
        //    {
        //        extend: 'pdfHtml5',
        //        className: 'btn btn-xs btn-primary p-5 m-0 width-35 assets-export-btn export-pdf ttip',
        //        title: 'Data export'
        //    }
        //]
          });
        });
    @* }); *@

</script>
<script>
    function click_update(val) {
        $.ajax({
            //url :"/controller_name/action_name"
            url: "/CategoryModels/EditCategory",
            datatype: "json",
            type: "get",
            data: { id: val },
            success: function (response) {
                // alert(JSON.stringify(response));
                //$(.class).val(response.must_be_same_as_value_that_alert)
                $('.Category_id').val(response.cateID);
                $('.Cate_name').val(response.cateName);
                $('.catenamekh').val(response.cateNameKH);


            },
            error: function (err) {
                console.log("Error get datae :" + err);
            }
        });
    }


    function click_delete(val) {
        swal({
            title: "Are you sure?",
            text: "Once deleted, you will not be able to recover this CategoryList!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {

                $.ajax({
                    url: "/CategoryModels/DeleteCategory",
                    datatype: "json",
                    type: "post",
                    data: { id: val },
                    success: function (response) {
                        //   alert(JSON.stringify(response));

                        if (response.data) {
                            // swal("Good job!", "User has been deleted !", "success");
                            swal({
                                icon: 'success',
                                title: 'Good job!',
                                text: 'CategoryList has been deleted !',
                                timer: 1500
                            })
                            setTimeout(function () { window.location.href = "/CategoryModels/CategoryList"; }, 2000);

                        }
                        else {
                            swal("Oops!", "Something went wrong !", "error");
                        }


                    },
                    error: function (err) {
                        console.log("Error get datae :" + err);
                    }
                });

            } else {
                swal("Your CategoryList is safe!");
            }
        });

    }
</script>

<!--Validate script jquery-->
<script>
    var $registrationForm = $('#frmModalCreate');
    if ($registrationForm.length) {
        $registrationForm.validate({
            rules: {
                CateName: {
                    required: true
                },
                CateNameKH: {
                    required: true
                },
            },
            messages: {

                CateName: {
                    required: 'Please enter CateName  !'
                },
                CateNameKH: {
                    required: 'Please enter CateNameKH !'
                }
            },
            errorPlacement: function (error, element) {
                if (element.is(":radio")) {
                    error.appendTo(element.parents('.gender'));
                }
                else if (element.is(":checkbox")) {
                    error.appendTo(element.parents('.hobbies'));
                }
                else {
                    error.insertAfter(element);
                }

            }
        });
    }

</script>